# Generated by Django 5.1.7 on 2025-03-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='make_pages.basecontent')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='SEO friendly url, use only aplhabets and hyphen')),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('button', models.CharField(blank=True, max_length=512)),
                ('btn_link', models.CharField(blank=True, max_length=512)),
                ('icon', models.CharField(blank=True, max_length=512, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='make_pages.heading')),
            ],
            options={
                'verbose_name_plural': 'Heading and Paragraph',
            },
            bases=('make_pages.basecontent',),
        ),
        migrations.CreateModel(
            name='ImagePage',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='make_pages.basecontent')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='section/%y/%m/%d/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='make_pages.imagepage')),
            ],
            bases=('make_pages.basecontent',),
        ),
    ]
