# Generated by Django 5.1.7 on 2025-03-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0002_heading_imagepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='make_pages.basecontent')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gmail', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact US',
            },
            bases=('make_pages.basecontent',),
        ),
    ]
