# Generated by Django 5.1.7 on 2025-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0004_rename_paragraph_contactus_message_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/%y/%m/%d/'),
        ),
    ]
