# Generated by Django 5.1.7 on 2025-03-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0005_heading_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='make_pages.basecontent')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('constructions_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price_of_constructions', models.BigIntegerField(blank=True, null=True)),
                ('bed', models.PositiveIntegerField(blank=True, null=True)),
                ('sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('bath', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/%y/%m/%d/')),
                ('address', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            bases=('make_pages.basecontent',),
        ),
    ]
