# Generated by Django 5.1.7 on 2025-03-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
