# Generated by Django 5.1.7 on 2025-03-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0007_imagepage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='constructions_status',
            field=models.PositiveIntegerField(choices=[(1, 'Ongoing'), (2, 'Completed'), (3, 'Happy Customer')], default=1),
        ),
    ]
