# Generated by Django 5.1.7 on 2025-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0011_propertyagent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyagent',
            old_name='icon',
            new_name='icon_1',
        ),
        migrations.AddField(
            model_name='propertyagent',
            name='icon_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyagent',
            name='icon_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
