# Generated by Django 5.1.7 on 2025-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pages', '0012_rename_icon_propertyagent_icon_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
